version: "3.8"

services:
    node:
        build:
            context: resources/docker/node
        restart: on-failure
        ports:
            - $NODE_PORT:3000
        environment:
            - NODE_ENV=dev
        volumes:
            - ./:/home/node/web
        networks:
            - default
        command: "npm start"

    mysql:
        image: mysql:5.7
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        ports:
            - $MYSQL_PORT:3306
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - default

networks:
    default:
        ipam:
            driver: default
            config:
                - subnet: $SUBNET

volumes:
    mysql: